### ISSUE TITLE
Trimming the Message

### ISSUE THREAD

**Issue by joshp23** [eternal-flame-AD/gotify-broadcast#2]
Nice functionality. Perfect for my use case.
Is there a way to trim the following data from the broadcast?:
```
============== 
Sent with gotify-broadcast plugin. 

Sender: uName (Admin) 
Channel: ChName 
Priority: 5 
```

**Comment by eternal-flame-AD** [comment]
This part is added to make sure that the user would be able to identify where the message came from, so they can set the correct filter if they do not want these messages to be delivered. I personally do not mind this tail added to the message, but if we really need to design a mechanism to trim this tail off, I would add another action in addition to `accept` and `reject`, something like `accept-trim`, which accepts the message and does not add this tail to the message ending.

I don't think this is really needed, but I would be happy to merge it if you could open a PR for this.

**Comment by joshp23** [comment]
If I have time. Day job in full effect will likely prevent this, however.

**Comment by eternal-flame-AD** [comment]
Closing as stale
