### ISSUE TITLE
Doesn't seem to want to work against gotify v2.0.19

### ISSUE THREAD

**Issue by AmandaCameron** [eternal-flame-AD/gotify-broadcast#4]
I've spent a good part of this afternoon trying to get this working with v2.0.19 -- seems no matter what I do something's out of alignment for the versions between the plugin and the base program.

Any help/suggestions would be appreciated.

**Comment by eternal-flame-AD** [comment]
Hi, 
I'm sorry I have not been able to keep this project updated with upstream yet, but if there is something I would say to try is to build the server and plugin from source so they should have the same package signature then.

Thanks,

**Comment by Jodrik** [comment]
We just got everything working for version 0.3.0 of the plugin
