### ISSUE TITLE
Error when add plugin

### ISSUE THREAD

**Issue by JamesDAdams** [eternal-flame-AD/gotify-broadcast#5]
Impossible to use the plugin with my gotify install, i have this error : 

`panic: error while loading plugin broadcasts-linux-amd64-for-gotify-v2.0.22.so: plugin.Open("data/plugins/broadcasts-linux-amd64-for-gotify-v2.0.22"): plugin was built with a different version of package gopkg.in/yaml.v2`

**Comment by JamesDAdams** [comment]
UP

**Comment by eternal-flame-AD** [comment]
Sorry for not keeping an eye on new releases, I added the new missing gotify versions onto the build queue and pushed a new release tag. I tested and it is loading correctly on my end now on the newest gotify release.

https://github.com/eternal-flame-AD/gotify-broadcast/releases/tag/v0.3.1

**Comment by JamesDAdams** [comment]
It's a abandoned project ?

**Comment by JamesDAdams** [comment]
Thanks
