### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by felixq** [eternal-flame-AD/gotify-broadcast#7]
I am trying to install the plugin on Gotify version 2.2.4 and I am getting the following errors:

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x8d62e1e9ec8210?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000054f50 sp=0xc000054f30 pc=0x70f876
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000054fe0 sp=0xc000054f50 pc=0x6f13b1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x73e901
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 5 [select]:
runtime.gopark(0xc00005b788?, 0x2?, 0x11?, 0x0?, 0xc00005b784?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005b610 sp=0xc00005b5f0 pc=0x70f876
runtime.selectgo(0xc00005b788, 0xc00005b780, 0x0?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc00005b750 sp=0xc00005b610 pc=0x71ee7c
database/sql.(*DB).connectionOpener(0xc0000e0c30, {0x153edd8, 0xc00035ca80})
        /usr/local/go/src/database/sql/sql.go:1224 +0x8d fp=0xc00005b7b8 sp=0xc00005b750 pc=0xc995cd
database/sql.OpenDB.func1()
        /usr/local/go/src/database/sql/sql.go:792 +0x2e fp=0xc00005b7e0 sp=0xc00005b7b8 pc=0xc9788e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005b7e8 sp=0xc00005b7e0 pc=0x73e901
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:792 +0x18d

goroutine 6 [chan receive]:
runtime.gopark(0x1a7f640?, 0xc00005bee8?, 0x3d?, 0x24?, 0x7fa1197835b8?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00005be68 sp=0xc00005be48 pc=0x70f876
runtime.chanrecv(0xc00010ef60, 0xc00005bf70, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc00005bef8 sp=0xc00005be68 pc=0x6db7fb
runtime.chanrecv1(0x0?, 0x0?)
        /usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc00005bf20 sp=0xc00005bef8 pc=0x6db2f8
github.com/gotify/server/v2/plugin.NewManager.func1()
        /proj/plugin/manager.go:69 +0xd2 fp=0xc00005bfe0 sp=0xc00005bf20 pc=0xd62e32
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x73e901
created by github.com/gotify/server/v2/plugin.NewManager
        /proj/plugin/manager.go:67 +0x252

**Comment by eternal-flame-AD** [comment]
Thanks, I added the new releases of gotify onto the build list and verified that v2.2.4 builds and runs. Can you check if it runs on your end as well?

**Comment by felixq** [comment]
Thanks, it works now.
