### ISSUE TITLE
Creating a build for new releases

### ISSUE THREAD

**Issue by StarZNighT** [eternal-flame-AD/gotify-broadcast#9]
Not really a new "issue" but an issue for me for sure.
I've installed for the first time the v2.5.0 gotify server in ubuntu and would like to try your plugin before having a workaround to send same app notif to lots of user.
Now since i'm kinda noob in building projects via go and github could you please write a mini how-to from scratch(i know you already wrote something in the readme but sadly it didn't worked)?
Or just release the version of the plugin compatible with the latest server :)
Thanks in advance!

**Comment by eternal-flame-AD** [comment]
@StarZNighT Thanks, I will make that happen by thursday. I am building an automated CI that follows Gotify release automatically which should be deployed in a few weeks.

**Comment by StarZNighT** [comment]
Thanks a lot!
For a golang newbie like me is a lifesaver ahahah
(To create the other ticket i downgraded gotify to 2.3.0 XD)

**Comment by eternal-flame-AD** [comment]
I created the releases! I'll keep this open to track the CI automation development.
